version: "3"

services:
  db:
    container_name: db-postgres
    image: postgres:9.6.8-alpine
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
